version: '3.4'
services:
  test:
    build:
      context: .
    environment:
      client_url: 'http://client:3000'
      api_url: 'http://api:3000'
      minio_url: 'http://minio:9000'
      temporal_url: 'temporal:7233'
      wiremock_url: 'http://wiremock:8080'
    depends_on:
      client:
        condition: service_healthy
    volumes:
      - ./tests:/tests/tests
      - ./utils:/tests/utils
