version: '3.4'
services:
  test:
    build:
      context: .
    environment:
      client_url: 'http://client:3000'
      api_url: 'http://api:3000'
      minio_url: 'http://minio:9000'
      wiremock_url: 'http://wiremock:8080'
      temporal_address: 'temporal:7233'
      temporal_ui_url: 'http://temporal-ui:8233'
      import_controller_url: 'http://import-controller:5000'
    depends_on:
      client:
        condition: service_healthy
    volumes:
      - ./tests:/tests/tests
      - ./utils:/tests/utils
